# Generated by Django 5.2.1 on 2025-10-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('utilities', 'Utilities'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
